namespace HealthComp.myCare.BulkUploadAdmins.Constants;

public static class Constants
{
    public  const string SourceExcelFilePath = "/Users/ritwik.gupta/Desktop/myCare/ExcelUpload/Testing_dev.xlsx";
    private const Environments Environment = Environments.Dev;
    public static string BearerToken = "eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM5Mjc0IiwibmFtZSI6InJnc2FkZXYiLCJnaXZlbm5hbWUiOiJSIiwic3VybmFtZSI6IkciLCJlbWFpbCI6InJpdHdpay5ndXB0YUBwZXJzb25pZnloZWFsdGguY29tIiwibmFtZWlkZW50aWZpZXIiOiIxNWM1MDAyNy05NzAzLTRjNTEtYmQ1OS04NDkwODYxNzdiNWIiLCJncm91cE51bWJlciI6IjExOTU5NSIsImVtcGxveWVyTmFtZSI6IkFuZGVzIENhbmRpZXMgTGxjIiwicm9sZSI6IkFkbWluIiwidXNlclJvbGUiOiIyIiwiYWxsR3JvdXBBY2Nlc3MiOiJGYWxzZSIsInBlcm1pc3Npb25zIjpbIkFkZGl0aW9uYWxSZXBvcnRzLkRlbGV0ZSIsIkFkZGl0aW9uYWxSZXBvcnRzLkVkaXQiLCJBZGRpdGlvbmFsUmVwb3J0cy5QSElBY2Nlc3MiLCJBZGRpdGlvbmFsUmVwb3J0cy5WaWV3IiwiQWRtaW4uUmVzb3VyY2VzLkNvbmZpZ3VyZSIsIkFkbWluLlJlc291cmNlcy5Db25maWd1cmUuQWxsIiwiQWRtaW4uUmVzb3VyY2VzLlZpZXciLCJBZG1pbk5vdGVzLkFkZCIsIkFkbWluVGFiLkNvbmZpZ3VyYXRpb25zLlZpZXciLCJBZG1pblRhYi5SZXBvcnRzLlZpZXciLCJBbm5vdW5jZW1lbnRzLkFkZCIsIkFubm91bmNlbWVudHMuRGVsZXRlIiwiQW5ub3VuY2VtZW50cy5FZGl0IiwiQW5ub3VuY2VtZW50cy5TZWxlY3QuR3JvdXAiLCJBbm5vdW5jZW1lbnRzLlZpZXciLCJCYWxhbmNlQmlsbC5JbnF1aXJ5VHlwZSIsIkJhbGFuY2VCaWxsaW5nLkZvcm0uRWRpdCIsIkJhbGFuY2VCaWxsaW5nLkZvcm0uVmlldyIsIkNsYWltTm90ZXMuVmlldyIsIkNsYWltcy5NeUhlYWx0aCIsIkNsYWltcy5Ub290aENoYXJ0IiwiQ2xhaW1zLlZpZXciLCJDbGluaWNhbFByb2dyYW1zLkVkaXQuUGxhbnMuR3JvdXAiLCJDbGluaWNhbFByb2dyYW1zLlNlY3Rpb24uRGVzY3JpcHRpb24uRWRpdC5Hcm91cCIsIkNsaW5pY2FsUHJvZ3JhbXMuU3lzdGVtLkVkaXQuQ2hlY2suR3JvdXAiLCJDbGluaWNhbFByb2dyYW1zLlN5c3RlbS5WaWV3IiwiQ29udGFjdC5FZGl0IiwiQ29udGFjdC5WaWV3IiwiQ29yZUJlbmVmaXRzLlBsYW5zLlZpZXciLCJDb3JlQmVuZWZpdHMuU2VjdGlvbi5EZXNjcmlwdGlvbi5FZGl0Lkdyb3VwIiwiQ29yZUJlbmVmaXRzLlN5c3RlbS5FZGl0LkJ1dHRvblRleHQiLCJDb3JlQmVuZWZpdHMuU3lzdGVtLkVkaXQuVXJsIiwiQ29yZUJlbmVmaXRzLlRpbGUuVG9nZ2xlLlZpZXciLCJDb3JlQmVuZWZpdHMuVmlldyIsIkN1c3RvbUJlbmVmaXRzLkFkZCIsIkN1c3RvbUJlbmVmaXRzLkRlbGV0ZSIsIkN1c3RvbUJlbmVmaXRzLkVkaXQiLCJDdXN0b21CZW5lZml0cy5TZWN0aW9uLldhcm5pbmcuRWRpdCIsIkN1c3RvbUJlbmVmaXRzLlZpZXciLCJGaW5kQ2FyZS5FZGl0IiwiRmluZENhcmUuVmlldyIsIkdsb2JhbC5Hcm91cFNlbGVjdC5WaWV3IiwiR3JvdXBFbnJvbGxtZW50Rm9ybXMuRWRpdCIsIkdyb3VwRW5yb2xsbWVudEZvcm1zLlZpZXciLCJHcm91cE5vdGVzLkFkZCIsIkdyb3VwU3Vic2NyaXB0aW9uLkVkaXQiLCJHcm91cFN1YnNjcmlwdGlvbi5WaWV3IiwiSGVhbHRoQWxlcnQuQ2FsZW5kbHkuVmlldyIsIkhlYWx0aEFsZXJ0LkNhcmVHYXBzLlZpZXciLCJIZWFsdGhNYXRjaC5TbWFydFJlZmZlcmFsLlZpZXciLCJIZWFsdGhNYXRjaE1hbmFnZXIuVmlldyIsIklEQ2FyZC5WaWV3IiwiSW1wZXJzb25hdGUuTWVtYmVyIiwiSW50cmFuZXQuTWVzc2FnaW5nLlZpZXciLCJNZW1iZXJzLkhlYWx0aFN1bW1hcnkiLCJNZW1iZXJzLkxpc3QuVmlldyIsIk1lbWJlclN1bW1hcnkuTm90ZXMuVmlldyIsIk1lbWJlclN1bW1hcnkuUHJlQ2xhaW0uVmlldyIsIk1lc3NhZ2luZy5JbnF1aXJ5VHlwZS5DbGluaWNhbCIsIk1lc3NhZ2luZy5Ob3RpZmljYXRpb24uVmlldyIsIk1lc3NhZ2luZy5WaWV3IiwiUHJlY2VydHMuQXBwZWFsIiwiUHJlY2VydHMuTWFudWFsLkFkZCIsIlByZWNlcnRzLlZpZXciLCJQcmltYXJ5VGlsZXMuQWRkIiwiUHJpbWFyeVRpbGVzLkFsbG93TWFuYWdlVG9nZ2xlLlZpZXciLCJQcmltYXJ5VGlsZXMuRGVsZXRlIiwiUHJpbWFyeVRpbGVzLkVkaXQiLCJQcmltYXJ5VGlsZXMuRWRpdC5DaGVjayIsIlByaW1hcnlUaWxlcy5QcmltYXJ5VG9nZ2xlLlZpZXciLCJQcmltYXJ5VGlsZXMuU3lzdGVtLlZpZXciLCJQcmltYXJ5VGlsZXMuVmlldyIsIlJlbWluZGVyLlBhc3N3b3JkRXhwaXJlZCIsIlJlbWluZGVyLlBhc3N3b3JkRXhwaXJpbmciLCJSZXBvcnRzLkhDTmF2aWdhdG9yLlZpZXciLCJSZXBvcnRzLlByb3ZpZGVyRW5nYWdlbWVudC5WaWV3IiwiUmVzb3VyY2VzLkZvcm1zLkRlbGV0ZSIsIlJlc291cmNlcy5Gb3Jtcy5FZGl0IiwiUmVzb3VyY2VzLkZvcm1zLlRvZ2dsZS5WaWV3IiwiUmVzb3VyY2VzLkdyb3VwLlNlY3Rpb24uQ3JlYXRlIiwiUmVzb3VyY2VzLkdyb3VwLlNlY3Rpb24uRGVsZXRlIiwiUmVzb3VyY2VzLkdyb3VwLlNlY3Rpb24uRWRpdCIsIlJlc291cmNlcy5Hcm91cC5TZWN0aW9uLlZpZXciLCJSZXNvdXJjZXMuR3JvdXAuU2VjdGlvbkl0ZW1zLkNyZWF0ZSIsIlJlc291cmNlcy5Hcm91cC5TZWN0aW9uSXRlbXMuRGVsZXRlIiwiUmVzb3VyY2VzLkdyb3VwLlNlY3Rpb25JdGVtcy5FZGl0IiwiUmVzb3VyY2VzLlNlYXJjaC5JdGVtcyIsIlJlc291cmNlcy5Vc2VmdWxMaW5rcy5JdGVtcy5BZGQiLCJSZXNvdXJjZXMuVXNlZnVsTGlua3MuSXRlbXMuRGVsZXRlIiwiUmVzb3VyY2VzLlVzZWZ1bExpbmtzLkl0ZW1zLkVkaXQiLCJSZXNvdXJjZXMuVXNlZnVsTGlua3MuVmlldyIsIlJlc291cmNlcy5WaWV3IiwiUm9sZVBlcm1pc3Npb25zLkVkaXQiLCJSb2xlcy5BZGQiLCJSb2xlcy5FZGl0IiwiUm9sZXMuVmlldyIsIlNlY29uZGFyeVRpbGVzLkFkZCIsIlNlY29uZGFyeVRpbGVzLkFsbG93TWFuYWdlVG9nZ2xlLlZpZXciLCJTZWNvbmRhcnlUaWxlcy5EZWxldGUiLCJTZWNvbmRhcnlUaWxlcy5FZGl0IiwiU2Vjb25kYXJ5VGlsZXMuRWRpdC5DaGVjayIsIlNlY29uZGFyeVRpbGVzLlByaW1hcnlUb2dnbGUuVmlldyIsIlNlY29uZGFyeVRpbGVzLlN5c3RlbS5WaWV3IiwiU2Vjb25kYXJ5VGlsZXMuVmlldyIsIlNpbmdsZS1TaWduLU9uLkluaXRpYXRlIiwiU3VwcGxlbWVudGFsQmVuZWZpdHMuRWRpdC5QbGFucy5Hcm91cCIsIlN1cHBsZW1lbnRhbEJlbmVmaXRzLlNlY3Rpb24uRGVzY3JpcHRpb24uRWRpdCIsIlN1cHBsZW1lbnRhbEJlbmVmaXRzLlNlY3Rpb24uRGVzY3JpcHRpb24uRWRpdC5Hcm91cCIsIlN1cHBsZW1lbnRhbEJlbmVmaXRzLlN5c3RlbS5FZGl0LkNoZWNrLkdyb3VwIiwiU3VwcGxlbWVudGFsQmVuZWZpdHMuU3lzdGVtLlZpZXciLCJTdXBwbGVtZW50YWxCZW5lZml0cy5Ub2dnbGUuVmlldyIsIlRlY2hTdXBwb3J0Lk1lbWJlckNyZWRzLlVwZGF0ZSIsIlRoZW1pbmdTZWN0aW9uLkNob29zZVN0eWxlLkVkaXQiLCJUaGVtaW5nU2VjdGlvbi5DdXN0b20iLCJUaGVtaW5nU2VjdGlvbi5FZGl0IiwiVGhlbWluZ1NlY3Rpb24uUGFyZW50RGVmYXVsdCIsIlVNTWVkaWNhbFJlY29yZHMuVmlldyIsIlVzZWZ1bExpbmsuUHJpbWFyeVRvZ2dsZS5WaWV3IiwiVXNlcnMuQWRkIiwiVXNlcnMuRGVsZXRlIiwiVXNlcnMuRWRpdCIsIlVzZXJzLlZpZXciXSwic2Vzc2lvbmlkIjoiODBkN2NhMjQtODc1NC00ODEzLTgwM2MtOTY0MjM3NTVkZjVlIiwiZXhwIjoxNzM1MzEyNjI1LCJpc3MiOiJodHRwczovL2hlYWx0aENvbXAuY29tIiwiYXVkIjoiaHR0cHM6Ly9oZWFsdGhDb21wLmNvbSJ9.S1OUbZ-L2B8Ugf7HyCvHjrCPo6QLmirkMmaMMD_DyZI";
    public static string RegisterAdminEndpoint
    {
        get
        {
            switch (Environment)
            {
                case Environments.Dev:
                case Environments.Qa:
                    return "https://hc-mycare-auth-api-dev.azurewebsites.net/api/v1/Users";
                case Environments.Staging:
                    return "https://hc-mycare-auth-api-staging.azurewebsites.net/api/v1/Users";
                case Environments.Prod:
                    return "https://hc-mycare-auth-api-prod.azurewebsites.net/api/v1/Users";
            }
        }
    }
}

public enum Environments
{
    Dev,
    Qa,
    Staging,
    Prod
}